// Libellés français maintenus à la main quand ceux de PokeAPI ne conviennent pas à l'affichage.

/**
 * Méthodes de rencontre : PokeAPI fournit des phrases ("En marchant dans les herbes
 * hautes ou une grotte"), on veut un libellé court pour les tableaux. Clé = slug PokeAPI.
 * La phrase complète reste disponible en anglais dans `nameEn`.
 */
export const METHOD_LABELS_FR: Record<string, string> = {
  walk: "Herbes hautes / grotte",
  "old-rod": "Canne",
  "good-rod": "Super Canne",
  "super-rod": "Méga Canne",
  surf: "Surf",
  "rock-smash": "Éclate-Roc",
  headbutt: "Coup d'Boule",
  "dark-grass": "Herbes sombres",
  "grass-spots": "Herbes mouvantes",
  "cave-spots": "Nuage de poussière",
  "bridge-spots": "Ombre de pont",
  "super-rod-spots": "Méga Canne (endroit sombre)",
  "surf-spots": "Surf (endroit sombre)",
  "yellow-flowers": "Fleurs jaunes",
  "purple-flowers": "Fleurs violettes",
  "red-flowers": "Fleurs rouges",
  "rough-terrain": "Terrain accidenté",
  gift: "Cadeau",
  "gift-egg": "Œuf en cadeau",
  static: "Rencontre fixe",
  pokeflute: "Pokéflûte",
  "headbutt-low": "Coup d'Boule (taux bas)",
  "headbutt-normal": "Coup d'Boule (taux normal)",
  "headbutt-high": "Coup d'Boule (taux élevé)",
  "squirt-bottle": "Carapuce à O",
  "wailmer-pail": "Seau Wailmer",
  seaweed: "Algues (plongée)",
  "roaming-grass": "Errant (herbes)",
  "roaming-water": "Errant (eau)",
  "devon-scope": "Devon Scope",
  "feebas-tile-fishing": "Pêche (case Barpau)",
  "island-scan": "Scan des Îles",
  sos: "Appel SOS",
  "bubbling-spots": "Point à bulles",
  "berry-trees": "Arbre à baies",
  "npc-trade": "Échange PNJ",
  "sos-from-bubbling-spot": "Appel SOS (point à bulles)",
  overworld: "Monde extérieur",
  "overworld-water": "Monde extérieur (eau)",
  "overworld-flying": "Monde extérieur (ciel)",
  "overworld-special": "Apparition rare",
  "overworld-flying-special": "Apparition rare (ciel)",
  "overworld-water-special": "Apparition rare (eau)",
  horde: "Horde",
  "colosseum-bonus-disc-us": "Disque bonus Colosseum (US)",
  "colosseum-bonus-disc-jpn": "Disque bonus Colosseum (JP)",
  "pokemon-channel-pal": "Pokémon Channel (PAL)",
  "pokemon-ranger": "Pokémon Ranger",
  "pokemon-battle-revolution": "Pokémon Battle Revolution",
  "new-york-pokecenter-wish-eggs": "Œuf Vœu (Pokémon Center NY)",
  snag: "Snag",
  "snag-rematch": "Snag (revanche)",
  pokespot: "Poké Place",
  "hidden-grotto": "Trouée cachée",
  "honey-tree": "Arbre à Miel",
  "overworld-dirt": "Monde extérieur (terre)",
  wanderer: "Emplacement fixe",
  "wanderer-water": "Emplacement fixe (eau)",
  "chase-water": "Poursuite (eau)",
  "dynamax-adventure": "Expédition Dynamax",
  "max-raid": "Raid Dynamax",
  "trash-can-ambush": "Embuscade (poubelle)",
  "rustling-bush-ambush": "Embuscade (buisson)",
  "ceiling-ambush": "Embuscade (plafond)",
  "ground-ambush": "Embuscade (sol)",
  "sky-ambush": "Embuscade (ciel)",
};

/** Versions dont le nom PokeAPI est ambigu (les originaux japonais s'appellent aussi Rouge/Bleu). */
export const VERSION_LABELS_FR: Record<string, string> = {
  "red-japan": "Rouge (Japon)",
  "green-japan": "Vert (Japon)",
  "blue-japan": "Bleu (Japon)",
};
